#ifndef TOKEN_H
#define TOKEN_H

typedef enum {
    TOKEN_INT, TOKEN_RETURN, TOKEN_IF, TOKEN_ELSE, TOKEN_WHILE, TOKEN_FOR,
    TOKEN_CONTINUE, TOKEN_BREAK, TOKEN_SWITCH, TOKEN_CASE, TOKEN_DEFAULT,
    TOKEN_STRUCT,

    TOKEN_IDENTIFIER,
    TOKEN_NUMBER,

    TOKEN_LPAREN, TOKEN_RPAREN,
    TOKEN_LBRACE, TOKEN_RBRACE,
    TOKEN_SEMICOLON, TOKEN_COMMA,
    TOKEN_ASSIGN,
    TOKEN_PLUS, TOKEN_MINUS, TOKEN_STAR, TOKEN_SLASH,
    TOKEN_EQ, TOKEN_NEQ, TOKEN_LT, TOKEN_GT, TOKEN_LE, TOKEN_GE,

    TOKEN_EOF,
    TOKEN_UNKNOWN
} TokenType;

typedef struct {
    TokenType type;
    char* lexeme;
} Token;

#endif
